import { NgModule } from '@angular/core';

import {MdAutocompleteModule, MdButtonModule,  MdButtonToggleModule,
  MdCardModule,
  MdChipsModule,
  MdCheckboxModule,
  MdDialogModule,
  MdGridListModule,
  MdIconModule,
  MdInputModule,
  MdListModule,
  MdMenuModule,
  MdProgressBarModule,
  MdProgressSpinnerModule,
  MdRadioModule,
  MdRippleModule,
  MdSelectModule,
  MdSidenavModule,
  MdSliderModule,
  MdSlideToggleModule,
  MdSnackBarModule,
  MdTabsModule,
  MdToolbarModule,
  MdTooltipModule,
  OverlayModule,
  PortalModule,
  RtlModule,
  StyleModule,
  A11yModule,
  PlatformModule,
  CompatibilityModule,
  ObserveContentModule} from '@angular/material';


@NgModule({
  imports: [
    // CommonModule,
    // MdAutocompleteModule,
    MdButtonModule,
    // MdCardModule,
    // MdChipsModule,
    // MdCheckboxModule,
    // MdGridListModule,
    // MdInputModule,
    MdListModule,
    // MdProgressBarModule,
    // MdProgressSpinnerModule,
    // MdRippleModule,
    // MdSelectModule,
    // MdSidenavModule,
    // MdTabsModule,
    // MdToolbarModule,
    // PortalModule,
    // RtlModule,
    // ObserveContentModule,
    // // These modules include providers.
    // A11yModule,
    // MdButtonToggleModule,
    // MdDialogModule,
    MdIconModule,
    MdMenuModule,
    // MdRadioModule,
    // MdSliderModule,
    // MdSlideToggleModule,
    // MdSnackBarModule,
    // MdTooltipModule,
    // PlatformModule,
    // OverlayModule,
    // CompatibilityModule.forRoot(),
  ],
  declarations: [],
  exports: [
    // CommonModule,
    // MdAutocompleteModule,
    MdButtonModule,
    // MdCardModule,
    // MdChipsModule,
    // MdCheckboxModule,
    // MdGridListModule,
    // MdInputModule,
    MdListModule,
    // MdProgressBarModule,
    // MdProgressSpinnerModule,
    // MdRippleModule,
    // MdSelectModule,
    // MdSidenavModule,
    // MdTabsModule,
    // MdToolbarModule,
    // PortalModule,
    // RtlModule,
    // ObserveContentModule,
    // // These modules include providers.
    // A11yModule,
    // MdButtonToggleModule,
    // MdDialogModule,
    MdIconModule,
    MdMenuModule,
    // MdRadioModule,
    // MdSliderModule,
    // MdSlideToggleModule,
    // MdSnackBarModule,
    // MdTooltipModule,
    // PlatformModule,
    // OverlayModule,
    // CompatibilityModule.forRoot(),
  ],
})
export class AppMaterialModule { }
